### PR TITLE
Disable HTTP/2

### PR DESCRIPTION
**Pull request by MikeEdgar**
MGDSTRM-8107

Signed-off-by: Michael Edgar <medgar@redhat.com>

### CODE REVIEW

**Comment by rareddy** [comment]
I believe @shawkins added a way from Strimzi configmap to add the ENV properties if you want to take that route too.

**Comment by shawkins** [comment]
> I believe @shawkins added a way from Strimzi configmap to add the ENV properties if you want to take that route too.

It's not wired in automatically, it's just that the fleetshard_operands.yaml can accommodate that if needed.

**Comment by MikeEdgar** [comment]
As I was committing this change I was wishing we had it ready :-)

> > I believe @shawkins added a way from Strimzi configmap to add the ENV properties if you want to take that route too.
> 
> It's not wired in automatically, it's just that the fleetshard_operands.yaml can accommodate that if needed.

**Review by rareddy — APPROVED** [review]
lgtm

**Pull request merged**
