### PR TITLE
[MGDSTRM-9401] Disable idempotence and retries for producer endpoint

### PR DESCRIPTION
**Pull request by MikeEdgar**
Bump Kafka test broker images and client to use version 3.2

### CODE REVIEW

**Review by rareddy — APPROVED** [review]
lgtm

reading the docs, if you do not explicitly set it, but reducing the ACKs to not all also has a similar effect. But I like the explicit setting better.

**Comment by biswassri** [comment]
@MikeEdgar Just wanted to confirm, that you're also upgrading the dependencies for Kafka 3.2.1, right? [[MGDSTRM-9328](https://issues.redhat.com/browse/MGDSTRM-9328)]

**Comment by MikeEdgar** [comment]
> upgrading the dependencies for Kafka 3.2.1

Yes, I hadn't noticed that issue.

**Comment by biswassri** [comment]
> Yes, I hadn't noticed that issue.

No worries! I just wanted confirm it.

**Review by biswassri — APPROVED** [review]
Lgtm

**Pull request merged**
