### PR TITLE
[MGDSTRM-9301] Generate certificates in Java and upgrade IT Keycloak

### PR DESCRIPTION
**Pull request by MikeEdgar**
Also add Makefile for easier dev startup, remove old env and IDE configurations from pre-Quarkus migration.

Signed-off-by: Michael Edgar <medgar@redhat.com>

### CODE REVIEW

**Review by biswassri — APPROVED** [review]
Just one question, how can I test this?

**Comment by MikeEdgar** [comment]
> Just one question, how can I test this?

The GitHub CI tests the system tests themselves and you can try the new `make dev` and `make dev-tls` commands in dev mode. They will leverage `docker-compose` and `dev-tls` will generate and deploy Kafka with TLS enabled.

**Comment by biswassri** [comment]
Thanks Mike!

**Comment by biswassri** [comment]
@MikeEdgar Lgtm, the changes work fine for me

**Pull request merged**
